let data = [
  {
    id: 0,
    en: "English",
    enex: "Flashcards.",
    de: "Deutsch",
    deex: "¡ Langenscheidt Grundwortschatz Englisch",
    grade: 0,
    comment: new Date(),
  },
  {
    id: 1,
    en: "to be called",
    enex: "He’s called Mario.",
    de: "heißen",
    deex: "Er heißt Mario.",
    grade: 0,
    comment: "",
  },
  {
    id: 2,
    en: "name",
    enex: "Could you spell your name please?",
    de: "der Name",
    deex: "Könnten Sie bitte Ihren Namen buchstabieren?",
    grade: 0,
    comment: "",
  },
  {
    id: 3,
    en: "surname",
    enex: "What’s your mother’s surname?",
    de: "der Familienname",
    deex: "Wie ist der Familienname deiner Mutter?",
    grade: 0,
    comment: "",
  },
  {
    id: 4,
    en: "last name",
    enex: "What’s your mother’s last name?",
    de: "der Nachname",
    deex: "Wie ist der Nachname deiner Mutter? ",
    grade: 0,
    comment: "",
  },
  {
    id: 5,
    en: "first name",
    enex: "My first name is Swedish.",
    de: "der Vorname",
    deex: "Mein Vorname ist schwedisch.",
    grade: 0,
    comment: "",
  },
  {
    id: 6,
    en: "single",
    enex: "I’m not single. My husband lives in Mexico.",
    de: "ledig",
    deex: "Ich bin nicht ledig. Mein Mann lebt in Mexiko. ",
    grade: 0,
    comment: "",
  },
  {
    id: 7,
    en: "singles",
    enex: "I was at a party with lots of singles.",
    de: "die Singles",
    deex: "Ich war bei einer Party mit lauter Singles.",
    grade: 0,
    comment: "",
  },
  {
    id: 8,
    en: "married",
    enex: "Since when have you been married?",
    de: "verheiratet",
    deex: "Seit wann sind Sie verheiratet?",
    grade: 0,
    comment: "",
  },
  {
    id: 9,
    en: "divorced",
    enex: "James and Carol were married, but now they’re divorced.",
    de: "geschieden",
    deex: "James und Carol waren verheiratet  aber jetzt sind sie geschieden.",
    grade: 0,
    comment: "",
  },
  {
    id: 10,
    en: "separated",
    enex: "Their parents aren’t separated. They just live in different flats.",
    de: "getrennt",
    deex: "Ihre Eltern sind nicht getrennt. Sie leben nur in verschiedenen Wohnungen. ",
    grade: 0,
    comment: "",
  },
  {
    id: 11,
    en: "widower",
    enex: "Peter’s wife died very young and he’s been a widower for most of his life.",
    de: "der Witwer",
    deex: "Peters Frau starb sehr jung, und er ist fast sein Leben lang Witwer. ",
    grade: 0,
    comment: "",
  },
  {
    id: 12,
    en: "Mr",
    enex: "This is my boss Mr Paul Brown.",
    de: "der Herr",
    deex: "Das ist mein Chef Herr Paul Brown.",
    grade: 0,
    comment: "",
  },
  {
    id: 13,
    en: "man",
    enex: "He’s a good-looking man.",
    de: "der Mann",
    deex: "Er ist ein gut aussehender Mann.",
    grade: 0,
    comment: "",
  },
  {
    id: 14,
    en: "Mrs",
    enex: "Is there a Mrs Bolton living in this ouse?",
    de: "die Frau",
    deex: "Wohnt in diesem Haus eine Frau Bolton?",
    grade: 0,
    comment: "",
  },
  {
    id: 15,
    en: "woman",
    enex: 'The novel is called "A Woman of Thirty".',
    de: "die Frau",
    deex: 'Der Roman heißt "Eine Frau von dreißig Jahren."',
    grade: 0,
    comment: "",
  },
  {
    id: 16,
    en: "Ms",
    enex: "Do you need any help, Ms Carlton?",
    de: "die Frau",
    deex: "Brauchen Sie Hilfe, Frau Carlton?",
    grade: 0,
    comment: "",
  },
  {
    id: 17,
    en: "Æ Ms ist  die  heute  gängige  Bezeichnung  für  Frauen  allgemein,  die  alte  Anrede Miss (Fräulein) wird jedoch noch von der älteren Generation für junge Mädchen und für Wendungen wie „Miss Germany“ verwendet.",
    enex: "xxx",
    de: "xxx",
    deex: "xxx",
    grade: 0,
    comment: "",
  },
  {
    id: 18,
    en: "baby   m/f",
    enex: "Peter is seven years old, Anne is still a baby.",
    de: "das Baby",
    deex: "Peter ist sieben Jahre alt, Anne ist noch ein Baby.",
    grade: 0,
    comment: "",
  },
  {
    id: 19,
    en: "child  pl children",
    enex: "We’re expecting our third child in une.",
    de: "das Kind",
    deex: "Im Juni erwarten wir unser drittes Kind.",
    grade: 0,
    comment: "",
  },
  {
    id: 20,
    en: "boy",
    enex: "There are only three boys in our lass.",
    de: "der Junge",
    deex: "In unserer Klasse sind nur drei Jungen.",
    grade: 0,
    comment: "",
  },
  {
    id: 21,
    en: "girl",
    enex: "Both my girls play in the same baseball team.",
    de: "das Mädchen",
    deex: "Meine beiden Mädchen spielen im selben Baseballteam.",
    grade: 0,
    comment: "",
  },
  {
    id: 22,
    en: "to call",
    enex: "His name is Robert, but we call him ob.",
    de: "nennen",
    deex: "Sein Name ist Robert, aber wir nennen ihn Rob.",
    grade: 0,
    comment: "",
  },
  {
    id: 23,
    en: "widow",
    enex: "After the death of her husband she founded an Internet forum for idows.",
    de: "die Witwe",
    deex: "Nach dem Tod ihres Gatten gründete sie ein Internetforum für Witwen.",
    grade: 0,
    comment: "",
  },
  {
    id: 24,
    en: "widowed",
    enex: "He has been widowed for many ears.",
    de: "verwitwet",
    deex: "Er ist seit vielen Jahren verwitwet.",
    grade: 0,
    comment: "",
  },
  {
    id: 25,
    en: "to come from ",
    enex: "Where do you come from?",
    de: "herkommen",
    deex: "Wo kommen Sie her?",
    grade: 0,
    comment: "",
  },
  {
    id: 26,
    en: "to be from ",
    enex: "She’s from Toronto, Canada.",
    de: "kommen aus",
    deex: "Sie kommt aus Toronto, Kanada.",
    grade: 0,
    comment: "",
  },
  {
    id: 27,
    en: "(place of) residence ",
    enex: "What’s your permanent place of residence?",
    de: "der Wohnort, der Wohnsitz",
    deex: "Was ist Ihr ständiger Wohnort?",
    grade: 0,
    comment: "",
  },
  {
    id: 28,
    en: "address",
    enex: "What’s your address?",
    de: "die Adresse, die Anschrift",
    deex: "Wie ist Ihre Adresse?",
    grade: 0,
    comment: "",
  },
  {
    id: 29,
    en: "street",
    enex: "She lives at 735 Willard Street.",
    de: "die Straße",
    deex: "Sie wohnt in der Willard-Straße 735.",
    grade: 0,
    comment: "",
  },
  {
    id: 30,
    en: "house number",
    enex: "No, the house number is 24, not 34.",
    de: "die Hausnummer",
    deex: "Nein, die Hausnummer ist 24, nicht 34.",
    grade: 0,
    comment: "",
  },
  {
    id: 31,
    en: "telephone number ",
    enex: "His office has a new telephone number: it’s 894-7866.",
    de: "die Telefonnummer",
    deex: "Sein Büro hat eine neue Telefonnummer: Sie lautet 894-7866.",
    grade: 0,
    comment: "",
  },
  {
    id: 32,
    en: "person   m/f,  pl people",
    enex: "die Person",
    de: "Tickets for the game are $24 per erson.",
    deex: "Die Eintrittskarten für das Spiel kosten 24 Dollar pro Person.",
    grade: 0,
    comment: "",
  },
  {
    id: 33,
    en: "marital status",
    enex: "der Familienstand",
    de: "Why did they ask for your marital tatus?",
    deex: "Warum haben sie nach deinem amilienstand gefragt?",
    grade: 0,
    comment: "",
  },
  {
    id: 34,
    en: "gender",
    enex: "das Geschlecht",
    de: "Nobody should be discriminated gainst because of their gender.",
    deex: "Niemand sollte wegen seines Geschlechts benachteiligt werden.",
    grade: 0,
    comment: "",
  },
  {
    id: 35,
    en: "nationality",
    enex: "die Staatsangehörigkeit, ie Staatsbürgerschaft",
    de: "In London you can see people of many different nationalities.",
    deex: "In London kann man Menschen mit vielen verschiedenen Staatsangehörigkeiten sehen.",
    grade: 0,
    comment: "",
  },
  {
    id: 36,
    en: "citizen",
    de: "der Staatsbürger, die Staatsbürgerin",
    enex: "All people born in the US can  become American citizens.",
    deex: "Alle Menschen, die in den USA geboren wurden, können amerikanische Staatsbürger werden.",
    grade: 0,
    comment: "",
  },
  {
    id: 37,
    en: "of age",
    enex: "volljährig",
    de: "I look younger but I am of age.",
    deex: "Ich sehe jünger aus, aber ich bin schon volljährig.",
    grade: 0,
    comment: "",
  },
  {
    id: 38,
    en: "Æ Je nach Land oder US-Bundesstaat ist man mit 18, 19 oder 21 Jahren volljährig. Man sagt also häufig, man sei over 18, um auszudrücken, dass man volljährig ist bzw. under 18, wenn man das Alter noch nicht erreicht hat.",
    enex: "xxx",
    de: "xxx",
    deex: "xxx",
    grade: 0,
    comment: "",
  },
  {
    id: 39,
    en: "under age ",
    enex: "minderjährig",
    de: "They didn’t let her in. She’s still under age.",
    deex: "Sie haben sie nicht reingelassen. Sie ist noch minderjährig.",
    grade: 0,
    comment: "",
  },
  {
    id: 40,
    en: "nickname",
    enex: "der Spitzname",
    de: "My nickname is Speedy.",
    deex: "Mein Spitzname ist Speedy.",
    grade: 0,
    comment: "",
  },
  {
    id: 41,
    en: "Charaktereigenschaften",
    enex: "xxx",
    de: "xxx",
    deex: "xxx",
    grade: 0,
    comment: "",
  },
  {
    id: 42,
    en: "good",
    enex: "gut, lieb, brav",
    de: "Greg’s a really good cook.",
    deex: "Greg ist ein wirklich guter Koch.",
    grade: 0,
    comment: "",
  },
  {
    id: 43,
    en: "impolite",
    enex: "unhöflich",
    de: "Would it be very impolite to leave",
    deex: "Wäre es sehr unhöflich, jetzt zu gehen?",
    grade: 0,
    comment: "",
  },
  {
    id: 44,
    en: "rough",
    enex: "Jodi’s boyfriend can be quite rough.",
    de: "grob",
    deex: "Jodis Freund kann ziemlich grob ein.",
    grade: 0,
    comment: "",
  },
  {
    id: 45,
    en: "pleasant",
    enex: "Her boss seems a very pleasant woman.",
    de: "sympathisch",
    deex: "Ihre Chefin scheint eine sehr sympathische Frau zu sein.",
    grade: 0,
    comment: "",
  },
  {
    id: 46,
    en: "unpleasant",
    enex: "He sounded somewhat unpleasant on the phone.",
    de: "unsympathisch",
    deex: "Er klang etwas unsympathisch am Telefon.",
    grade: 0,
    comment: "",
  },
  {
    id: 47,
    en: "lazy",
    enex: "You wouldn’t believe how lazy I can e.",
    de: "faul",
    deex: "Du würdest nicht glauben, wie faul ich sein kann.",
    grade: 0,
    comment: "",
  },
  {
    id: 48,
    en: "cheerful",
    enex: "I’m always cheerful in the mornings.",
    de: "fröhlich, heiter",
    deex: "Ich bin morgens immer fröhlich.",
    grade: 0,
    comment: "",
  },
  {
    id: 49,
    en: "funny",
    enex: "My new boyfriend is so funny. He nows hundreds of jokes.",
    de: "lustig, komisch",
    deex: "Mein neuer Freund ist so lustig. Er kennt Hunderte von Witzen.",
    grade: 0,
    comment: "",
  },
  {
    id: 50,
    en: "entertaining",
    enex: "His performance as Harry Potter was really entertaining.",
    de: "unterhaltsam",
    deex: "Seine Darbietung als Harry Potter war wirklich unterhaltsam.",
    grade: 0,
    comment: "",
  },
  {
    id: 51,
    en: "calm",
    enex: "Even though Jack hadn’t passed the test, his father stayed calm.",
    de: "ruhig",
    deex: "Obwohl Jack den Test nicht bestan- den hatte, blieb sein Vater ruhig.",
    grade: 0,
    comment: "",
  },
  {
    id: 52,
    en: "clever",
    enex: "What a clever girl you are.",
    de: "schlau",
    deex: "Was für ein schlaues Mädchen du doch bist.",
    grade: 0,
    comment: "",
  },
  {
    id: 53,
    en: "stupidity",
    enex: "His stupidity is incredible: today he asked me if chickens lay eggs.",
    de: "die Dummheit",
    deex: "Seine Dummheit ist unglaublich: Heute hat er mich gefragt, ob Hühner Eier legen.",
    grade: 0,
    comment: "",
  },
  {
    id: 54,
    en: "stupid",
    enex: "There are no stupid questions, only tupid answers.",
    de: "dumm",
    deex: "Es gibt keine dummen Fragen, sondern nur dumme Antworten.",
    grade: 0,
    comment: "",
  },
  {
    id: 55,
    en: "courage",
    enex: "Don’t lose courage!",
    de: "der Mut",
    deex: "Verlier den Mut nicht!",
    grade: 0,
    comment: "",
  },
  {
    id: 56,
    en: "brave",
    enex: "It was brave of Kyle to jump into the ice-cold water to save the little girl.",
    de: "mutig",
    deex: "Es war mutig von Kyle, in das eiskalte Wasser zu springen, um das leine Mädchen zu retten.",
    grade: 0,
    comment: "",
  },
  {
    id: 57,
    en: "cowardly",
    enex: "That was a cowardly lie.",
    de: "feige",
    deex: "Das war eine feige Lüge.",
    grade: 0,
    comment: "",
  },
  {
    id: 58,
    en: "to be used to",
    enex: "I’m used to getting up early.",
    de: "gewöhnt sein an",
    deex: "Ich bin daran gewöhnt, früh aufzustehen.",
    grade: 0,
    comment:
      "Æ to be used to doing sth. – daran gewöhnt sein, etw. zu tun verwendet man, um auszudrücken, dass man etwas regelmäßig und nicht ungern tut, man kann die Phrase in allen Zeitstufen verwenden. Die ähnlich klingende Wendung used to do sth. bedeutet, dass man in der Vergangenheit etwas häufig getan hat, aber heute nicht mehr tut. Es wird meist mit früher übersetzt.",
  },
  {
    id: 59,
    en: "personality",
    enex: "You need a strong personality to work for this company.",
    de: "die Persönlichkeit",
    deex: "Um bei dieser Firma zu arbeiten, raucht man eine starke Persönlichkeit.",
    grade: 0,
    comment: "",
  },
  {
    id: 60,
    en: "character",
    enex: "He’s a man of character.",
    de: "der Charakter",
    deex: "Er ist ein Mann von Charakter.",
    grade: 0,
    comment: "",
  },
  {
    id: 61,
    en: "honesty",
    enex: "Tyler’s honesty is not in question.",
    de: "die Ehrlichkeit",
    deex: "Tylers Ehrlichkeit steht nicht infrage.",
    grade: 0,
    comment: "",
  },
  {
    id: 62,
    en: "honest",
    enex: "I’m glad she was honest with me.",
    de: "ehrlich",
    deex: "Ich bin froh, dass sie ehrlich zu mir war.",
    grade: 0,
    comment: "",
  },
  {
    id: 63,
    en: "sincerely",
    enex: "I sincerely hope he’s not ill again.",
    de: "wirklich, aufrichtig",
    deex: "Ich hoffe aufrichtig, dass er nicht wieder krank ist.",
    grade: 0,
    comment: "",
  },
  {
    id: 64,
    en: "open",
    enex: "The new manager is open and friendly.",
    de: "offen",
    deex: "Der neue Manager ist offen und freundlich.",
    grade: 0,
    comment: "",
  },
  {
    id: 65,
    en: "generous",
    enex: "großzügig",
    de: "It was very generous of Matthew to pay for the dinner.",
    deex: "Es war sehr großzügig von Matthew, das Abendessen zu bezahlen.",
    grade: 0,
    comment: "",
  },
  {
    id: 66,
    en: "stingy",
    enex: "geizig",
    de: "Some people are so stingy, they’d rather re than turn on the heating.",
    deex: "Manche Menschen sind so geizig, dass sie im Winter lieber frieren als die Heizung anzustellen.",
    grade: 0,
    comment: "",
  },
  {
    id: 67,
    en: "sense of humour ",
    enex: "Angela has a wonderful sense of Humour. You should meet her.",
    de: "der Humor",
    deex: "Angela hat einen wundervollen Humor. Du solltest sie kennenlernen.",
    grade: 0,
    comment: "",
  },
  {
    id: 68,
    en: "mood",
    enex: "die Laune",
    de: "Don’t talk to Sam, he’s in a bad mood.",
    deex: "Sprich Sam nicht an, er hat schlechte Laune.",
    grade: 0,
    comment: "",
  },
  {
    id: 69,
    en: "curiosity",
    enex: "die Neugierde",
    de: "Danny read the letter out of curiosity.",
    deex: "Danny hat den Brief aus Neugierde gelesen.",
    grade: 0,
    comment: "",
  },
  {
    id: 70,
    en: "curious",
    enex: "neugierig",
    de: "I’m curious to know what he did.",
    deex: "Ich bin neugierig zu erfahren, was er getan hat.",
    grade: 0,
    comment: "",
  },
  {
    id: 71,
    en: "ambitious",
    enex: "ehrgeizig",
    de: "Annabel is an ambitious young oman with clear career objectives.",
    deex: "Annabel ist eine ehrgeizige junge Frau mit klaren Karrierezielen.",
    grade: 0,
    comment: "",
  },
  {
    id: 72,
    en: "passion",
    enex: "die Leidenschaft",
    de: "My brother has a passion for good food.",
    deex: "Mein Bruder hat eine Leidenschaft für gutes Essen.",
    grade: 0,
    comment: "",
  },
  {
    id: 73,
    en: "passionate",
    enex: "leidenschaftlich",
    de: "They had a short but passionate affair.",
    deex: "Sie hatten eine kurze, aber leidenschaftliche Affäre.",
    grade: 0,
    comment: "",
  },
  {
    id: 74,
    en: "naughty",
    enex: "ungezogen",
    de: "Her children are so naughty at times.",
    deex: "Ihre Kinder sind manchmal so ungezogen.",
    grade: 0,
    comment: "",
  },
  {
    id: 75,
    en: "sensitive",
    enex: "empfindlich, sensibel",
    de: "He should stop making fun of Katie. He knows she’s very sensitive.",
    deex: "Er sollte aufhören, sich über Katie lustig zu machen. Er weiß, dass sie sehr sensibel ist.",
    grade: 0,
    comment: "",
  },
  {
    id: 76,
    en: "Æ Das deutsche sensibel heißt sensitive, das englische sensible bedeutet vernünftig.",
    enex: "xxx",
    de: "xxx",
    deex: "xxx",
    grade: 0,
    comment: "",
  },
  {
    id: 77,
    en: "nervous",
    enex: "nervös",
    de: "Go away! You’re making me nervous.",
    deex: "Geh weg! Du machst mich nervös.",
    grade: 0,
    comment: "",
  },
  {
    id: 78,
    en: "shy",
    enex: "schüchtern",
    de: "I’d love to go out with Jenny but I’m too shy to ask her.",
    deex: "Ich würde gern mit Jenny ausgehen, ber ich bin zu schüchtern, sie zu fragen.",
    grade: 0,
    comment: "",
  },
  {
    id: 79,
    en: "modest",
    enex: "bescheiden",
    de: "Although he is very successful he’s always remained modest.",
    deex: "Obwohl er sehr erfolgreich ist, ist er immer bescheiden geblieben.",
    grade: 0,
    comment: "",
  },
  {
    id: 80,
    en: "mad",
    enex: "verrückt, wütend",
    de: "Hannah must be mad to spend so much money on CDs. or: Margret is mad because I lost her necklace.",
    deex: "Hannah muss verrückt sein, so viel Geld für CDs auszugeben. bzw. Margret ist wütend, weil ich ihr Halsband verloren habe.",
    grade: 0,
    comment: "",
  },
  {
    id: 81,
    en: "ridiculous",
    enex: "lächerlich",
    de: "Don’t be ridiculous!",
    deex: "Mach dich nicht lächerlich!",
    grade: 0,
    comment: "",
  },
  {
    id: 82,
    en: "reason",
    enex: "die Vernunft",
    de: "Reason is the ability to think in an intelligent way.",
    deex: "Die Vernunft ist die Fähigkeit, auf intelligente Weise zu denken.",
    grade: 0,
    comment: "",
  },
  {
    id: 83,
    en: "reasonable",
    enex: "vernünftig",
    de: "Be reasonable! It’s too expensive.",
    deex: "Sei vernünftig! Es ist zu teuer.",
    grade: 0,
    comment: "",
  },
  {
    id: 84,
    en: "pride",
    enex: "der Stolz",
    de: "Rachel hurt my pride when she said I was ugly.",
    deex: "Rachel hat meinen Stolz verletzt, als sie sagte, ich sei hässlich.",
    grade: 0,
    comment: "",
  },
  {
    id: 85,
    en: "proud",
    enex: "stolz",
    de: "The little girl was so proud of her new doll.",
    deex: "Das kleine Mädchen war so stolz auf ihre neue Puppe.",
    grade: 0,
    comment: "",
  },
];

export default data;
